// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {  
      throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Web - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    };
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKkNzWl_r1la6vkWAA3WBHZovhpXfVi5c',
    appId: '1:969058020811:android:c83d4798fb3b98e068da4e',
    messagingSenderId: '969058020811',
    projectId: 'carrent-ed9ee',
    storageBucket: 'carrent-ed9ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCijXXUQRj7GQMR-7ZeicrhgS3j0VG7m_E',
    appId: '1:961519639955:ios:4e1e6305b65a216f7f1c66',
    messagingSenderId: '961519639955',
    projectId: 'rentapp-fg-x',
    storageBucket: 'rentapp-fg-x.appspot.com',
    iosBundleId: 'com.example.rentapp',
  );

}